Add help menu and ability to run specific tests for validatecodeonce
SatelCreative/docker-python-base pull request #358
Opened 2022-06-30 02:52 UTC by estellajaysong

- Add help menu to validatecodeonce when you use the flag -
<img width="695" alt="Screen Shot 2022-06-29 at 7 20 44 PM" src="https://user-images.githubusercontent.com/39111549/176582503-2a3c1df0-eea7-4b73-b0f1-18adb57ae2fe.png">
h
- Add ability to select specific tests when you use the flag -k

2022-06-30 18:17 UTC, hillairet requested changes
The code looks great.
Documentation is needed though!

2022-06-30 18:29 UTC, estellajaysong commented
@hillairet Oh, right! This repo is well documented & looks good! :)

2022-07-15 15:57 UTC, hillairet requested changes
An example goes a long way. That would give me confidence that I know how to run it without running it.

2022-07-19 01:46 UTC, hillairet approved these changes

2022-07-19 02:23 UTC, rahulpatidar0191 approved these changes

2022-07-19 18:11 UTC, merged